title = "The R Dispatch"
baseURL = "https://therdispatch.netlify.app/"
languageCode = "en-us"
theme = "gohugo-theme-ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$", "\\_files$"]

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = "/images/favicon.ico"
  site_logo = "/images/rdispatch-white.png"
  description = "An R Centered Knowledge Base."
  facebook = ""
  twitter = "https://twitter.com/Jimmy82929796"
  instagram = ""
  youtube = ""
  github = "https://github.com/jimbrig"
  gitlab = ""
  linkedin = "www.linkedin.com/in/jimbrig"
  mastodon = ""
  slack = "https://app.slack.com/client/T018PCYSQQL/C018AFE4D0E"
  stackoverflow = "https://stackexchange.com/users/7999132/jimmy"
  rss = "https://feedly.com/i/subscription/feed%2Fhttps%3A%2F%2Ffeedly.com%2Ff%2FqOVW62nvaI7U3Fp6BLtRqKnY"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "images/background.jpg"
  recent_posts_number = 5
